{% set name = "pyscreener" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyscreener-{{ version }}.tar.gz
  sha256: 6e2df866643bc4ad424f4e20fd1e18a7aeb1b777e612f6e490f1359b13681c13

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - colorama
    - configargparse
    - h5py
    - numpy
    - pandas
    - pdbfixer
    - python >=3.8
    - ray-default
    - scipy
    - tqdm
    - openbabel
    - rdkit

test:
  imports:
    - pyscreener
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/coleygroup/pyscreener
  summary: pythonic interface to virtual screening software
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
